"""Generate the Go SDK from its pinned local Service contract.

Generation does not import, check out, or execute the Service. Check mode compares
both bytes and file names without replacing the committed generated directory.
"""

import argparse
import json
import shutil
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "codegen"
TARGET = ROOT / "generated"


def run(*args: str, cwd: Path = ROOT) -> None:
    subprocess.run(args, cwd=cwd, check=True)


def generate(document: dict, work: Path) -> Path:
    source = work / "openapi.json"
    source.write_text(json.dumps(document))
    output = work / "output"
    output.mkdir()
    run(
        "go",
        "run",
        "github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@v2.8.0",
        "--config",
        str(CONFIG / "config.yaml"),
        "-o",
        str(output / "client.gen.go"),
        str(source),
    )
    text = (output / "client.gen.go").read_text()
    secrets = "// Code generated by codegen/generate.py; DO NOT EDIT.\npackage generated\n\n"
    for name, schema in document["components"]["schemas"].items():
        if any(prop.get("writeOnly") for prop in schema.get("properties", {}).values()):
            assert f"type {name} struct" in text, f"Update the Go diagnostic adapter for {name}"
            secrets += f'func ({name}) String() string {{ return "{name} {{ .. }}" }}\n'
            secrets += f'func ({name}) GoString() string {{ return "{name} {{ .. }}" }}\n'
    (output / "secrets.gen.go").write_text(secrets)
    run("gofmt", "-w", str(output / "secrets.gen.go"))
    return output


def files(path: Path) -> dict[str, bytes]:
    return {
        str(file.relative_to(path)): file.read_bytes()
        for file in path.rglob("*")
        if file.is_file() and "__pycache__" not in file.parts
    }


def install(output: Path, target: Path, *, check: bool) -> bool:
    actual, expected = files(target), files(output)
    changed = sorted(name for name in actual.keys() | expected.keys() if actual.get(name) != expected.get(name))
    if not changed:
        return True
    if check:
        print(f"Stale generated files in {target.relative_to(ROOT)}: " + ", ".join(changed[:20]))
        return False
    # Only generator-owned directories are replaced, including removed schemas.
    if target.exists():
        shutil.rmtree(target)
    shutil.copytree(output, target)
    return True


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    document = json.loads((ROOT / "contract/openapi.json").read_text())
    with tempfile.TemporaryDirectory(prefix="a13n-codegen-") as temp:
        output = generate(document, Path(temp))
        if not install(output, TARGET, check=args.check):
            parser.exit(1, "SDK bindings changed. Run make generate and commit the result.\n")


if __name__ == "__main__":
    main()
