"""Generate the Go SDK from its pinned local Service contract.

Generation does not import, check out, or execute the Service.
"""

import json
import shutil
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "codegen"
TARGET = ROOT / "generated"


def run(*args: str, cwd: Path = ROOT) -> None:
    subprocess.run(args, cwd=cwd, check=True)


def generate(document: dict, work: Path) -> Path:
    source = work / "openapi.json"
    source.write_text(json.dumps(document))
    output = work / "output"
    output.mkdir()
    run(
        "go",
        "run",
        "github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@v2.8.0",
        "--config",
        str(CONFIG / "config.yaml"),
        "-o",
        str(output / "client.gen.go"),
        str(source),
    )
    text = (output / "client.gen.go").read_text()
    secrets = "// Code generated by codegen/generate.py; DO NOT EDIT.\npackage generated\n\n"
    for name, schema in document["components"]["schemas"].items():
        if any(prop.get("writeOnly") for prop in schema.get("properties", {}).values()):
            assert f"type {name} struct" in text, f"Update the Go diagnostic adapter for {name}"
            secrets += f'func ({name}) String() string {{ return "{name} {{ .. }}" }}\n'
            secrets += f'func ({name}) GoString() string {{ return "{name} {{ .. }}" }}\n'
    (output / "secrets.gen.go").write_text(secrets)
    run("gofmt", "-w", str(output / "secrets.gen.go"))
    return output


def install(output: Path, target: Path) -> None:
    # Only generator-owned directories are replaced, including removed schemas.
    if target.exists():
        shutil.rmtree(target)
    shutil.copytree(output, target)


def main() -> None:
    document = json.loads((ROOT / "contract/openapi.json").read_text())
    with tempfile.TemporaryDirectory(prefix="a13n-codegen-") as temp:
        install(generate(document, Path(temp)), TARGET)


if __name__ == "__main__":
    main()
